### ISSUE TITLE
Custom headers for Cookie based authentication

### ISSUE THREAD

**Issue by rsvasangh** [POLAR-fhiR/fhircrackr#115]
Hi, I need to access a FHIR server that supports cookie-based authentication. Does 'fhircrackr' support custom headers to define the key: value for the cookie? I would truly appreciate your timely response.

**Comment by palmjulia** [comment]
Hi! At the moment the fhircrackr doesn't support cookie based authentication but it should not be too hard to write a quick fix for that if I know your exact needs. 

I'm not very familiar with the topic so I'd appreciate a quick description of what you'd want to do. Do you *just* want to add a custom header to your request with a cookie that you've gotten somewhere else (i.e. that is avaible in you R working space as a string) or would the fhircrackr need to get the cookie from the server first? If the latter is the case, do you have to send username and password to get the cookie from the server in the first place and if so, to which address would that be sent exactly?
