### ISSUE TITLE
POST search with relative next links doesn't work

### ISSUE THREAD

**Issue by palmjulia** [POLAR-fhiR/fhircrackr#116]
Message from Essen:
Tatsächlich kann unser FHIR-server Post Search beantworten. 
Allerdings müssen die Werte in den next-links zu einer eigenen POST-Search Anfrage zusammengebaut werden. Ansonsten funktioniert die pagination nicht, indem man einfach in die Post-Anfrage einen Parameter "_shipPagination=eyJvZmZzZXQiOjEwMH0%3D" definiert. Der komplette Pfad für den next-link lautet nämlich "/app/FHIR/r4/Condition/_search?_count=100&_shipPagination=eyJvZmZzZXQiOjEwMH0%3D". Diese Query muss zu einer eigenen Post Anfrage zusammengebaut werden. 

Man kommt sowohl per POST als auch per GET auf die nächste Page. Die Variante mit GET-Requests ist aber deutlich einfacher.

```
'link": [ 
{ 
"relation": "self", 
"url": 
"/app/FHIR/r4/Condition?_count=100&_shipPagination=eyJvZmZzZXQiOjB9" 
}, 
{ 
"relation": "first", 
"url": 
"/app/FHIR/r4/Condition?_count=100&_shipPagination=eyJvZmZzZXQiOjB9" 
}, 
{ 
"relation": "next", 
"url": 
"/app/FHIR/r4/Condition?_count=100&_shipPagination=eyJvZmZzZXQiOjEwMH0% 
3D" 
} 
],
```

**Comment by karzideh** [comment]
I tried out the fix and I actually get 6 females born after 1990-01-01!

**Comment by palmjulia** [comment]
Nice! I'll update the documentation a bit, maybe you can ping me after you've successfully used it in the POLAR analysis. If that one works it's probably safe to merge it into the master :)

**Comment by karzideh** [comment]
Yeah sure I can do that. Thank you for the fix!
