### ISSUE TITLE
fixed file name pattern to function fhir_load prevents loading arbitrary named xml files

### ISSUE THREAD

**Issue by rennkater** [POLAR-fhiR/fhircrackr#118]
In file download_resources.R in line 623 there is a fixed regex for matching file names
`	files <- grep('^[0-9]+\\.xml$', dir(directory), value = T)`
This enforces all file names to start with a digit, which is to strict.
I would recommend to add a parameter with the default value, such that users can override the strict pattern, e.g.
```
fhir_load <- function(directory, indices = NULL, pattern = '^[0-9]+\\.xml$') {

	if(!dir.exists(directory)) {

		warning("Cannot find the specified directory.")

		return(fhir_bundle_list(list()))
	}

	files <- grep(pattern, dir(directory), value = T)

```

**Comment by palmjulia** [comment]
Completely valid feature request I'll add it do the development version asap. Thanks for the suggestion!

**Comment by palmjulia** [comment]
Just to check: Are you happy with the changes in the linked pull request or is there anything else you'd like to request regarding the loading process @rennkater ?

**Comment by rennkater** [comment]
> Just to check: Are you happy with the changes in the linked pull request or is there anything else you'd like to request regarding the loading process @rennkater ?

Hi @palmjulia , so far everything works fine, thank you. But I did not test everything yet.
