### ISSUE TITLE
Paging with relative links breaks when searching for `http://` type CodeSystems 

### ISSUE THREAD

**Issue by palmjulia** [POLAR-fhiR/fhircrackr#123]
```
request <- "https://mii-agiop-3p.life.uni-leipzig.de/fhir/Encounter?date=ge2018-01-01&class=https://www.medizininformatik-initiative.de/fhir/core/modul-fall/CodeSystem/Versorgungsfallklasse%7Cvollstationaer"

#doesnt work 
base <- stringr::str_match(request, ".*:\\/\\/.*?\\/")
```

**Comment by palmjulia** [comment]
@karzideh It was literally just one character that had to be changed. Could you test the following for me, when you find the time?

```
remotes::install_github("https://github.com/POLAR-fhiR/fhircrackr", ref = "fix_paging")

request <- "[base]/Encounter?date=sa2018-01-01&date=eb2021-12-31&_count=100&type=http://fhir.de/CodeSystem/Kontaktebene%7Ceinrichtungskontakt"

bundles <- fhir_search(request = request, 
					   max_bundles = 5,
					   [your authentication])
```

Just adjust the base url and you authentication info if necessary.

**Comment by karzideh** [comment]
I tested it on our fhir server and unfortunately, I only get two bundles as a result. Also the second Bundle seems to have no entries since the self.link is [/app/FHIR/r4/Encounter?date=sa2018-01-01&date=eb2021-12-31&date=eb2021-12-31&_count=1000&_count=1000&type=http://fhir.de/app/FHIR/r4/Encounter?date%3Dsa2018-01-01&type=http://fhir.de/CodeSystem/Kontaktebene%7Ceinrichtungskontakt&_shipPagination=eyJvZmZzZXQiOjEwMDB9](url)

I can give you more details if needed.

**Comment by palmjulia** [comment]
Oh that looks bad, thanks for testing! Could you give me the entire link list of the first bundle?
You can print the bundle to the console with `cat(toString(bundles[[1]]))`  and just copy the link bit from there.

**Comment by karzideh** [comment]
The link-list of the first bundle looks like this:

```
  <link>
    <relation value="self"/>
    <url value="/app/FHIR/r4/Encounter?date=sa2018-01-01&amp;date=eb2021-12-31&amp;_count=10&amp;type=http://fhir.de/CodeSystem/Kontaktebene%7Ceinrichtungskontakt&amp;_shipPagination=eyJvZmZzZXQiOjB9"/>
  </link>
  <link>
    <relation value="first"/>
    <url value="/app/FHIR/r4/Encounter?date=sa2018-01-01&amp;date=eb2021-12-31&amp;_count=10&amp;type=http://fhir.de/CodeSystem/Kontaktebene%7Ceinrichtungskontakt&amp;_shipPagination=eyJvZmZzZXQiOjB9"/>
  </link>
  <link>
    <relation value="next"/>
    <url value="/app/FHIR/r4/Encounter?date=sa2018-01-01&amp;date=eb2021-12-31&amp;_count=10&amp;type=http://fhir.de/CodeSystem/Kontaktebene%7Ceinrichtungskontakt&amp;_shipPagination=eyJvZmZzZXQiOjEwfQ%3D%3D"/>
  </link>
```

**Comment by palmjulia** [comment]
Hm. I cannot find out what went wrong, when I test it here, the next link is built correctly by the crackr. You did install the fhircrackr from the new branch before you tested, right? 

Maybe we could find a date to have look at it together sometime? I'll get in touch with you per mail.

**Comment by karzideh** [comment]
I installed the fhircrackr from the new branch with `remotes::install_github("https://github.com/POLAR-fhiR/fhircrackr", ref = "fix_paging")`

Sure, we can have look at it together.
