### ISSUE TITLE
BUG: fhircrack fhir_search function gets stuck

### ISSUE THREAD

**Issue by esalehi92** [POLAR-fhiR/fhircrackr#126]
Hi, 
I am currently trying to run a R-script on our Blaze-fhir-server but the script gets stuck when running the **fhir_search** function from **fhircrackr** library.

I testet it with simple queries and it works when only one condition is applied (e.g. icd-code = E84.0) but with more complex queries, it gets stuck (see screenshot below).
![fhir-protected2](https://user-images.githubusercontent.com/114484055/192528350-1efb5220-d7b7-4ec3-b791-6727c7f740b0.png)

and if I cancel the run via Ctrl+C, the error below is shown:
![fhir-protected](https://user-images.githubusercontent.com/114484055/192528042-836f8671-ad14-4c71-8592-a56a67d28e00.png)

I'd appreciate any help! Thank you

**Comment by palmjulia** [comment]
Hi, thanks for reporting. The error that's shown when you cancel is fine, I think that's just what happens when the curl request is canceld before there's a proper answer from the server.

Have you tried your request outside of R? That would be the first check, copy the request you're giving to `fhir_search()` into either a webbrowser or Postman (if you're using that) and let me know if you get back a bundle there. Thanks!

**Comment by esalehi92** [comment]
Hi, thank you for the quick response! 
Yes, you were right. 
The same query cannot be run via curl. 
But isn't there any timeout option or something similar to get a feedback if the query is not doing anything? Because there are different scenarios that it gets stuck! For example, for the same query that works, if I increase the number of counts and/or bundles, it also gets stuck in between!
look at the query and result in screenshots

![fhir4](https://user-images.githubusercontent.com/114484055/192548121-cff918be-f497-46ba-894d-849ba65047b7.png)
![fhir3](https://user-images.githubusercontent.com/114484055/192548103-7853ee1e-da2c-4fd7-bf35-2cd7baea2bc1.png)


It gets stuck in the middle! Can it be a performance issue? or maybe it is curling something that doesn't exist?
Thanks a lot!

**Comment by esalehi92** [comment]
Thank you for the help. It was neither a problem of fhircrackr nor R. There were performance bottlenecks causing it.
