### ISSUE TITLE
Documantation fhir_cast() - Example not working 

### ISSUE THREAD

**Issue by christian3Sf6** [POLAR-fhiR/fhircrackr#136]
The example from page 22 in the Documantation does not work.

bundles <- fhir_unserialize(bundles = example_bundles1)
table_desc <- fhir_table_description(resource = "Patient",brackets = c('[',']'),sep      = " ",keep_attr=TRUE)
df <- fhir_crack(bundles = bundles, design = table_desc)
fhir_cast(df, brackets=c('[',']'), sep ='', verbose = 0)

It gives:

Error in grep(id_str, indexed_df[[name]], perl = T) : 
  invalid regular expression '\[[]'
In addition: There were 50 or more warnings (use warnings() to see the first 50)
warnings():
1: In FUN(X[[i]], ...) :
  Column name 'address.city@value' doesn't fit the id pattern found in this column.The column name should be build the way fhir_crack() automatically builds it. See ?fhir_cast.
2: In FUN(X[[i]], ...) : NAs introduced by coercion

Seems like there is a bug in fhir_cast()

**Comment by palmjulia** [comment]
Hi! Thanks for reporting and sorry for the late reply. It seems you have lost something in the copy and paste process. The last line of code should be:

`fhir_cast(df, brackets=c('[',']'), sep =' ', verbose = 0)`

Your version is missing a blank space between the quotation marks for the `sep` argument and that is causing the error.

I realize however that it is unhelpful that the example uses both `"` and `'` for the definition of strings, I assume that's where the error came from. I'll fix this in the next version of the package.

**Comment by christian3Sf6** [comment]
Thanks for ur reply! The example works now like u explained it! Iwas thinking about the use of a white space characters like % for obligatory blank spaces in the code, but i think its not common in R.
