### ISSUE TITLE
New elements for fhir_table_description

### ISSUE THREAD

**Issue by palmjulia** [POLAR-fhiR/fhircrackr#59]
New elements:
- format: character length one, one of c("compact", "wide"), defaults to wide
- keep_attr: logical length one, defaults to FALSE

--> also  create corresponding arguments in fhirc_crack()

Remove fhir_style object: sep, brackets, rm_empty_cols go directly into fhir_table_description
Backwards Compatibility: When fhir_style is present in fhir_table_description, it is used as before. If elements are present in fhir_table_description too they are used but a (deprecation) warning is thrown. 

-->  fhir_crack argument overwrites fhir_table_description overwrites fhir_style

**Comment by TPeschel** [comment]
Done in Branch feature-crack-wide.
fhir_style is removed there
