### ISSUE TITLE
Check URL in fhir_url

### ISSUE THREAD

**Issue by TPeschel** [POLAR-fhiR/fhircrackr#87]
Check Argument url for beeing a real url via regex!
In case of a failure print a warning!

**Comment by TPeschel** [comment]
https://urlregex.com

**Comment by palmjulia** [comment]
Its actually quite hard finding the perfect regex for all possible urls including IP addresses. Plus fhir_search() will fail with an informative warning in case the url is wrong so closing this issue for now.
